- project:
    name: x/python-group-based-policy-client
    templates:
      - openstack-python3-victoria-jobs
      - publish-to-pypi
    # REVISIT: In the jobs below, the required-projects clause is needed on
    # the master branch to select the correct version of the requirements
    # repository. Otherwise, the master version will be used. It can be
    # eliminated on the stable branches, and on the master branch once this
    # repository's master branch is based on the neutron repository's master
    # branch.
    check:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-bionic
            ansible-version: 9
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
        - openstack-tox-py36:
            nodeset: ubuntu-bionic
            ansible-version: 9
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
        - openstack-tox-py37:
            nodeset: ubuntu-bionic
            ansible-version: 9
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
        - openstack-tox-py38:
            nodeset: ubuntu-focal
            voting: false
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
    gate:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-bionic
            ansible-version: 9
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
        - openstack-tox-py36:
            nodeset: ubuntu-bionic
            ansible-version: 9
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
        - openstack-tox-py37:
            nodeset: ubuntu-bionic
            ansible-version: 9
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
        - openstack-tox-py38:
            nodeset: ubuntu-focal
            voting: false
            required-projects:
              - name: openstack/requirements
                override-checkout: victoria-eol
